Repository monicahq/monica, pull requests merged in 2018-05, with the labels that each got.

#1117 Get list of countries from countries-laravel package
  .circleci/config.yml
  .circleci/config.yml.sig
  CHANGELOG
  app/Address.php
  app/Console/Commands/SetupTest.php
  app/Console/Commands/Update.php
  app/Country.php
  app/Helpers/CollectionHelper.php
  app/Helpers/CountriesHelper.php
  app/Helpers/LocaleHelper.php
  app/Http/Controllers/Api/ApiAddressController.php
  app/Http/Controllers/Api/Misc/ApiCountryController.php
  app/Http/Controllers/Contacts/AddressesController.php
  app/Http/Requests/People/AddressesRequest.php
  app/Http/Resources/Country/Country.php
  app/Http/ViewComposers/CountrySelectViewComposer.php
  app/ImportJob.php
  app/Jobs/ExportAccountAsSQL.php
  app/Traits/VCardImporter.php
  composer.json
  composer.lock
  config/countries.php
  config/debugbar.php
  database/factories/ModelFactory.php
  database/migrations/2018_05_06_061227_external_countries.php
  database/seeds/CountriesSeederTable.php
  database/seeds/DatabaseSeeder.php
  database/seeds/FakeContentTableSeeder.php
  phpunit.xml
  public/css/app.css.map
  public/js/app.js
  public/js/app.js.map
  public/js/manifest.js.map
  public/js/vendor.js.map
  public/mix-manifest.json
  resources/assets/js/components/people/Addresses.vue
  tests/Feature/AddressTest.php
  tests/Unit/AddressTest.php
  tests/Unit/CountriesTest.php
  tests/Unit/ImportVCardsTest.php
Labels: performances

#1112 Add #1056 Add a view of contacts who do not have tags associated with them [In review]
  CHANGELOG
  app/Contact.php
  app/Http/Controllers/ContactsController.php
  resources/lang/en/people.php
  resources/views/people/index.blade.php
  tests/Unit/ContactTest.php
Labels: feature request

#980 Allow multiple imported fields, replace existing
  CHANGELOG
  app/Http/Controllers/SettingsController.php
  app/ImportJob.php
  app/Jobs/AddContactFromVCard.php
  resources/lang/en/settings.php
  resources/views/settings/imports/index.blade.php
  resources/views/settings/imports/upload.blade.php
  tests/Unit/ImportJobTest.php
Labels: enhancement

#169 converted columns for emoji support
  config/database.php
  database/migrations/2018_05_24_203000_convert_mysql_encoding.php
Labels: database
