Repository monicahq/monica, pull requests merged in 2020-03, with the labels that each got.

#3218 feat: Allow editing middle name
  CHANGELOG.md
  CONTRIBUTORS
  app/Http/Controllers/ContactsController.php
  resources/views/people/create.blade.php
  resources/views/people/edit.blade.php
  tests/Feature/ContactTest.php
Labels: reviewed

#3481 feat: add ability to set me contact
  CHANGELOG.md
  app/Http/Controllers/Api/ApiContactController.php
  app/Http/Controllers/SettingsController.php
  app/Providers/AppServiceProvider.php
  app/Services/Contact/Contact/DeleteMeContact.php
  public/css/app-ltr.css
  public/css/app-rtl.css
  public/js/app.js
  public/js/langs/en.json
  public/js/vendor.js
  public/mix-manifest.json
  resources/js/app.js
  resources/js/components/dashboard/DashboardLog.vue
  resources/js/components/partials/Avatar.img.vue
  resources/js/components/partials/Avatar.vue
  resources/js/components/people/ContactSelect.vue
  resources/js/components/people/MeContact.vue
  resources/js/components/people/StayInTouch.vue
  resources/js/components/settings/ActivityTypes.vue
  resources/js/components/settings/Modules.vue
  resources/lang/en/settings.php
  resources/views/dashboard/index.blade.php
  resources/views/errors/402.blade.php
  resources/views/people/_header.blade.php
  resources/views/people/relationship/new.blade.php
  resources/views/settings/index.blade.php
  routes/api.php
  tests/Api/Contact/ApiContactControllerTest.php
  tests/Unit/Services/Contact/Contact/DeleteMeContactTest.php
Labels: ready for review

#3694 fix: Wrong untagged contacts counter
  CHANGELOG.md
  app/Http/Controllers/ContactsController.php
Labels: reviewed, waiting for answers
