Repository monicahq/monica, pull requests merged in 2020-12, with the labels that each got.

#4654 chore: change cypress workflow
  .github/workflows/cypress.yml
Labels: auto-squash

#4652 feat: add Swedish language
  config/lang-detector.php
  public/js/app.js
  public/js/langs/en.json
  public/js/vendor.js
  public/mix-manifest.json
  resources/lang/en/settings.php
  webpack.mix.js
Labels: auto-squash

#4653 chore: update sentry js library
  resources/views/errors/500.blade.php
Labels: auto-squash

#4563 refactor: refactor contacts sorting for readability
  app/Models/Contact/Contact.php
  tests/Feature/ContactTest.php
Labels: hacktoberfest-accepted

#4662 refactor: simplify commands exec and tests
  app/Console/Commands/Helpers/Command.php
  app/Console/Commands/Helpers/CommandCaller.php
  app/Console/Commands/Helpers/CommandCallerContract.php
  app/Console/Commands/Helpers/CommandExecutor.php
  app/Console/Commands/Helpers/CommandExecutorInterface.php
  app/Console/Commands/Passport.php
  app/Console/Commands/SentryRelease.php
  app/Console/Commands/Update.php
  app/Providers/AppServiceProvider.php
  tests/Commands/CommandExecutorTester.php
  tests/Commands/PassportCommandTest.php
  tests/Commands/UpdateCommandTest.php
  tests/Helpers/CommandCallerFake.php
Labels: auto-squash

#4663 chore: fix secrets mapping
  scripts/ci/fixsecrets.sh
Labels: auto-squash

#4627 docs: deploy on platform
  .platform.app.yaml
  .platform/services.yaml
  readme.md
  template-definition.yaml
Labels: waiting for answers
