Repository monicahq/monica, pull requests merged in 2021-05, with the labels that each got.

#5148 chore(release): update release 3.0.1
  CHANGELOG.md
Labels: auto-squash, semantic-release

#5000 style: Minor fixes to wording on people.php.
  resources/lang/en/people.php
  tests/Feature/RelationshipTest.php
Labels: reviewed

#5170 chore: adding laravel/tinker for development
  composer.json
  composer.lock
Labels: reviewed

#5103 feat: search notes when searching through contacts
  app/Helpers/SearchHelper.php
  app/Models/Contact/Contact.php
  tests/Unit/Helpers/SearchHelperTest.php
Labels: waiting for answers

#5136 feat: Datestamp filename of exported SQL file.
  app/Http/Controllers/SettingsController.php
  tests/Feature/SettingsTest.php
Labels: reviewed

#5097 feat: email field on add person
  app/Http/Controllers/ContactsController.php
  app/Services/Contact/Contact/CreateContact.php
  resources/lang/en/people.php
  resources/views/people/create.blade.php
  tests/Unit/Services/Contact/Contact/CreateContactTest.php
Labels: reviewed
