Repository monicahq/monica, pull requests merged in 2021-04, with the labels that each got.

#5109 chore(i18n): update translations
  public/js/langs/de.json
  public/js/langs/es.json
  public/js/langs/he.json
  resources/lang/de/people.php
  resources/lang/de/validation.php
  resources/lang/es/people.php
  resources/lang/es/validation.php
  resources/lang/he/people.php
  resources/lang/he/validation.php
Labels: auto-squash

#5110 chore(release): update release 2.21.0
  CHANGELOG.md
Labels: auto-squash, semantic-release

#5027 style: Remove google fonts (addresses #5025).
  resources/views/errors/layout.blade.php
  resources/views/marketing/skeleton.blade.php
Labels: reviewed

#5130 chore(i18n): update translations
  public/js/langs/cs.json
  public/js/langs/id.json
  public/js/langs/no.json
  public/js/langs/pt-BR.json
  public/js/langs/ru.json
  public/js/langs/vendor.json
  resources/lang/cs/people.php
  resources/lang/cs/validation.php
  resources/lang/id/app.php
  resources/lang/id/auth.php
  resources/lang/id/dashboard.php
  resources/lang/id/journal.php
  resources/lang/id/mail.php
  resources/lang/id/pagination.php
  resources/lang/id/passwords.php
  resources/lang/id/people.php
  resources/lang/id/validation.php
  resources/lang/no/app.php
  resources/lang/no/auth.php
  resources/lang/no/changelog.php
  resources/lang/no/dashboard.php
  resources/lang/no/format.php
  resources/lang/no/journal.php
  resources/lang/no/logs.php
  resources/lang/no/mail.php
  resources/lang/no/pagination.php
  resources/lang/no/passwords.php
  resources/lang/no/people.php
  resources/lang/no/reminder.php
  resources/lang/no/settings.php
  resources/lang/no/validation.php
  resources/lang/pt-BR/people.php
  resources/lang/ru/people.php
  resources/lang/ru/settings.php
  resources/lang/ru/validation.php
  resources/lang/vendor/confirmation/no/confirmation.php
  resources/lang/vendor/webauthn/no/errors.php
  resources/lang/vendor/webauthn/ru/errors.php
Labels: auto-squash

#5131 chore(release): update release 2.22.0
  CHANGELOG.md
Labels: auto-squash, semantic-release

#5132 chore(release): update release 2.22.1
  CHANGELOG.md
Labels: auto-squash, semantic-release

#5134 chore(release): update release 3.0.0
  CHANGELOG.md
Labels: auto-squash, semantic-release
